version: "3"
services:
  nidavellir:
    image: lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - $HOME/Valheim-Servers/config:/config
      - $HOME/Valheim-Servers/data:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - $HOME/Valheim-Servers/valheim.env
    restart: always
    stop_grace_period: 2m
